name: Create Branch from Issue

on:
  issues:
    types: [labeled]

jobs:
  create_branch:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.issue.labels.*.name, 'Feature') || 
      contains(github.event.issue.labels.*.name, 'Bug') || 
      contains(github.event.issue.labels.*.name, 'Hotfix') ||
      contains(github.event.issue.labels.*.name, 'Chore')
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set the branch prefix based on the issue label
        id: create_branch_name
        run: |
          LABEL=$(echo "${{ github.event.issue.labels[0].name }}" | tr '[:upper:]' '[:lower:]')
          ISSUE_TITLE=$(echo "${{ github.event.issue.title }}" | sed 's/[][]//g' | tr ' ' '-')
          ISSUE_NUMBER=${{ github.event.issue.number }}
          BRANCH_NAME="${LABEL}/${ISSUE_NUMBER}-${ISSUE_TITLE}"
          echo "Branch name: $BRANCH_NAME"
          echo "::set-output name=branch_name::$BRANCH_NAME"

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create and push branch
        env:
          TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          git checkout -b ${{ steps.create_branch_name.outputs.branch_name }}
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} ${{ steps.create_branch_name.outputs.branch_name }} --force

      - name: Link branch to issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Authorization: bearer $GITHUB_TOKEN" \
          -d '{"query": "mutation { createLinkedBranch(input:{branchName:\"${{ steps.create_branch_name.outputs.branch_name }}\", issueId:\"${{ github.event.issue.node_id }}\"}) { clientMutationId } }"}' \
          https://api.github.com/graphql
